export const ROUTES = {
  ALL: '/',
  CONCERT: '/concert',
  ART_GALLERY: '/art-gallery',
  SPORT: '/sport',
  OTHERS: '/others',
  CLEARANCE: '/clearance',
  LOGIN: '/login',
  SIGN_UP: '/sign-up',
  SIGN_UP_WITH_EMAIL: '/sign-up-email',
  SIGN_UP_WITH_SNS: '/sign-up-sns',
  FORGOT_PASSWORD: '/forgot-password',
  EVENT_DETAIL: '/event-page/detail/:id',
  // Buy Ticket
  BUY_TICKET: '/buy-ticket',
  // TICKET_SELECT_TRANSACTION: '/buy-ticket/transaction-method',
  TICKET_SELECT_TRANSACTION: '/buy-ticket/transaction-method',
  ORDER_TICKET: (id: string, methodDelivery: string) =>
    `/buy-ticket/transaction-method/order/${id}/method/${methodDelivery}`,

  EVENT_PAGES: '/event-page',
  TEST: '/test',
  REGISTER_TO_SELL: '/register-to-sell',
  SELECT_DELIVERY_AREA: '/register-to-sell/select-delivery-area',
  SELECT_DELIVERY_AREA_PHASE_3: '/register-to-sell/select-delivery-area-detail',
  SELL_TICKET: '/sell-ticket/:eventId',
  CONFIRM_TICKET: '/register-to-sell/confirm-ticket',
  API_AUTH_CALLBACK: '/api/auth/callback',
  PRODUCT_DETAILS: '/product-details/:id',
  REGISTRATION_SELLER: '/seller-registration',
  PAYMENT_CALLBACK: '/api/payment/callback',
  TERM_OF_USE: '/term-of-use',
};
export const ROUTE_USER = {
  USER_MY_PAGE: '/user/my-page',
  USER_WITHDRAWAL_MANAGE: '/user/withdrawal-manage',
  USER_MY_TICKET_SALES: '/user/my-ticket-sales',
  USER_MY_PURCHASES: '/user/my-purchases',
  USER_MY_COUPON: '/user/my-coupon',
  USER_PIN_NUMBER_BOX: '/user/pin-number-box',
  USER_NOTIFICATION: '/user/notification',
  USER_PRODUCT_COMPARISON: '/user/product-comparison',
  USER_FAQ: '/user/faq',
  USER_INQUIRY: '/user/inquiry',
  USER_CREATE_INQUIRY: '/user/inquiry/create',
  USER_DETAIL_INQUIRY: '/user/inquiry/:id',

  NOTIFICATION_DETAIL_PATTER: '/notification/:id',
  NOTIFICATION_DETAIL: (id: string) => `/notification/${id}`,
};

export const ROUTE_API = {
  OUT_SITE_TICKET: '/tickets/outside-ticket',
  EVENT_FILTER: '/events/filters',
  EVENT_TOP: '/events/list-top-event',
  ADDRESS: '/available-address',
  LOGIN: '/auth/sign-in',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  SIGN_UP: '/auth/sign-up',
  GET_INFO_KAKAO: '/auth/get-info-by-auth-code',
  CHANGE_PASSWORD: '/auth/change-password',
  EVENT: '/events',
  OUTSIDE_TICKET: '/outside-ticket',
  LOGIN_SNS: '/auth/sign-in-sns',
  USER_VOUCHER: '/voucher/user',
  USER_VOUCHER_AVAILABLE: '/voucher/user-available',
  USER_VOUCHER_ORDER: 'voucher/user-available',
  PROFILE: '/user/profile',
  ORDERS_SALES: '/orders/sales',
  ORDERS_PURCHASES: '/orders/purchases',
  ORDERS: '/orders',
  PURCHASE_STATUS_STATISTICS: '/orders/purchases/status-statistics',
  PURCHASE_PAYMENT_TO_SELLER: '/orders/purchases/payment-to-seller',
  ORDER_STATUS_STATISTICS: '/orders/sales/status-statistics',
  UPLOAD_PROOF_PIC: '/files/ticket/upload-proof-picture',
  PRE_CONFIRM_INSIDE_TICKET: '/tickets/pre-confirm/inside-ticket',
  CREATE_INSIDE_TICKET: '/tickets/inside-ticket',
  UPLOAD_FILE_MULTIPLE: 'files/upload-multiple-files',
  TICKET_SALES: '/tickets/ticket-sales',
  BUY_TICKET: '/tickets/inside-ticket/event',
  ORDERS_PRE_CONFIRM: '/orders/pre-confirm',
  CREATE_ORDER_PAYMENT: '/orders/payment',
  TICKET_SALES_CANCEL_LISTING: '/tickets/ticket-sales/cancel-listing',
  SEND_PIN_CODE: '/tickets/ticket-sales/send-pin',
  PIN_RECEIVED: '/tickets/pin/received',
  PIN_SENT: '/tickets/pin/sent',
  GET_NOTIFICATIONS: '/notifications/get-list',
  GET_NOTIFICATION_DETAIL: '/notifications',
  SENT_TICKET: '/tickets/ticket-sales/save-delivery-unit-info',
  NAVIGATION_CATEGORY: '/navigation-categories/get-list',

  INQUIRY: '/inqueries',
  INQUIRY_CREATE: '/inqueries/create',
  EVENT_SEARCH: '/events/search',
  OUT_SITE_TICKET_FILTER: '/tickets/outside-ticket/filters',
  FAQ_CATEGORY: '/faqs/categories',
  FAQ: '/faqs',
  PRE_CONFIRM_OUTSIDE_TICKET: '/tickets/pre-confirm/outside-ticket',
  PRODUCT_DETAIL: '/tickets/inside-ticket',

  USER_PROFILE: 'user/profile',

  BANK_ACCOUNT_SYSTEM: '/banks/get-all-system-banks',
  BANK: '/banks',
  GET_FGKEY: '/payment/eximbay/unlock/ready-fgkey',
  ORDER_PAYMENT: '/payment/eximbay/order/ready-fgkey',

  CREATE_SELLER: '/user/register-business-information',

  USER_INFORMATION_WITHDRAW: '/user/info-for-withdrawal',
  REQUEST_WITHDRAW: '/withdrawal-requests/create',
  GET_LIST_WITHDRAW_DETAIL: '/balance-histories/get-list',
  GET_LIST_WITHDRAW_HISTORY: '/withdrawal-requests/get-list',
  CREATE_REPORT_ORDER: '/report-order',
  SENT_OTP: '/auth/otp-email',
  GET_OTP: '/auth/get-otp-email',
  GET_STATE_REGISTER_BUSINESS:
    '/user/precondtion-for-register-business-information',
  GET_BANNER: '/banners',
  GET_DATA_VERIFY_NICE: '/nice/create-request-verify',
};
